#######################
### Import packages ###
#######################

from functions import *
import matplotlib.pyplot as plt
from hmmlearn import hmm
import sys
from IPython.core import ultratb
sys.excepthook = ultratb.FormattedTB(call_pdb=False)

plt.style.use('paper.mplstyle')

######################
### Mice selection ###
######################

# defining data folder path and mice list
# path_to_data_folder is the path of the folder where you store the folders of your different mice.
#path_to_data_folder='/LocalData/ForagingMice/4TowersTaskMethodPaper_Data/AurelienData/'
path_to_data_folder='/LocalData/ForagingMice/4TowersTaskMethodPaper_Data/MaudData/'

# Analysing the entire group of mice
# mice_to_analyse = [
#     "MOUEml1_5", "MOUEml1_8", "MOUEml1_11", "MOUEml1_12", "MOUEml1_13", "MOUEml1_15", "MOUEml1_18", "MOUEml1_20",
#     "MOURhoA_2", "MOURhoA_5", "MOURhoA_6", "MOURhoA_8", "MOURhoA_9", "MOURhoA_12", "MOURhoA_14",
#     "MOUB6NN_4", "MOUB6NN_6", "MOUB6NN_13", "MOUB6NN_15"
# ]

mice_to_analyse = ['MOU3974','MOU3975', 'MOU3987', 'MOU3988', 'MOU3991', 'MOU3992', 'MOU4551', 'MOU4552', 'MOU4560', 'MOU4561', 'MOU4562',
                   'MOU4563', 'MOU4623', 'MOU4964', 'MOU4965', 'MOU4986', 'MOU4987', 'MOU4988', 'MOU4993', 'MOU5007', 'MOU5008']

# Verify that all folders in mice_to_analyse are present in path_to_data_folder
missing_folders = [mouse for mouse in mice_to_analyse if not os.path.isdir(os.path.join(path_to_data_folder, mouse))]

##################
### Parameters ###
##################

training_mouse = mice_to_analyse[0]
validation_mouse = mice_to_analyse[1]

training_mouse_folder_path = os.path.join(path_to_data_folder, training_mouse)
validation_mouse_folder_path = os.path.join(path_to_data_folder, validation_mouse)

epoch_types = ['run_around_tower', 'run_between_towers', 'run_toward_tower', 'exploratory_run']
session_index = 19

######################
### Extract epochs ###
######################

training_ordered_epochs_types_number = extract_epoch_sequence(path_to_data_folder, training_mouse, session_index)
validation_ordered_epochs_types_number = extract_epoch_sequence(path_to_data_folder, training_mouse, session_index)

training_num_epoch = len(training_ordered_epochs_types_number)
validation_num_epoch = len(validation_ordered_epochs_types_number)

### Visualize data ###

fig=plt.figure(figsize=(4, 4), dpi=300, constrained_layout=False, facecolor='w')
gs = fig.add_gridspec(1, 1)
row1 = gs[0].subgridspec(2, 1)
ax1 = plt.subplot(row1[0])
ax2 = plt.subplot(row1[1])

plot_epoch_distribution(ax1, ordered_epochs_types_number)
plot_epoch_sequence(ax2, ordered_epochs_types_number)


###################
### Infer model ###
###################

emissions = np.int8(ordered_epochs_types_number.reshape(-1,1))

best_model, best_score = infer_best_model(emissions[:emissions.shape[0] // 2], emissions[emissions.shape[0] // 2:], [2,3,4], seed=13)

states = best_model.predict(emissions.reshape(-1,1))

print(f'Best score:      {best_score}')

#######################
### Visualize Model ###
#######################

# plot our recovered states compared to generated (aim 1)
fig, ax = plt.subplots()

ax.plot(abs(states-1) + 1.5, label='recovered')
ax.set_yticks([])
ax.set_title('States compared to generated')
ax.set_xlabel('Time (# rolls)')
ax.legend()


# plot a sequence generated by the model
fig=plt.figure(figsize=(4, 4), dpi=300, constrained_layout=False, facecolor='w')
gs = fig.add_gridspec(1, 1)
row1 = gs[0].subgridspec(2, 1)
ax1 = plt.subplot(row1[0])
ax2 = plt.subplot(row1[1])

gen_ordered_epochs_types_number, gen_states = best_model.sample(num_epoch)

plot_epoch_distribution(ax1, gen_ordered_epochs_types_number.reshape(1,-1)[0])
plot_epoch_sequence(ax2, gen_ordered_epochs_types_number.reshape(1,-1)[0])

plt.show()

print(f'Transmission Matrix Recovered:\n{best_model.transmat_.round(3)}\n\n')

print(f'Emission Matrix Recovered:\n{best_model.emissionprob_.round(3)}\n\n')


